spring:
  application:
    name: spring-cloud-service-account
  cloud:
    config:
      discovery:
        service-id: spring-cloud-config
        enabled: true
      profile: dev

server:
  port: 8902

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/