spring:
  application:
    name: spring-cloud-service-order
  cloud:
    config:
      discovery:
        enabled: true
        service-id: spring-cloud-config
      profile: dev

server:
  port: 8901

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/

feign:
  hystrix:
    enabled: true